FROM alpine:3.11.6

LABEL maintainer="marta.arcones@gmail.com"

## Whenever this environment variable is changed, the subsequent commands will run
ENV REFRESHED_AT 2020-26-04

RUN apk update && apk upgrade